/** @file diedialog.cpp
 *  @brief Stores implementations of DieDialog class.
 *
 *  This file contains implementations of a function besides default codes generated by Qt.
 */

#include "diedialog.h"
#include "ui_diedialog.h"
#include "mainwindow.h"

DieDialog::DieDialog(QWidget *parent) :
    QDialog(parent),
    ui(new Ui::DieDialog)
{
    ui->setupUi(this);


//    // Connect retry button with retry function.
//    QObject::connect(retry_button, SIGNAL(clicked(bool)), this, SLOT(retry()))
}

DieDialog::~DieDialog()
{
    delete ui;
}

/** Direct user to main menu after the function is called.
*/
void DieDialog::retry(){

    MainWindow* mainMenu = new MainWindow;
    mainMenu->setWindowTitle("Out of Inferno");
    mainMenu->show();
    this->hide();
}
