/** @file instructiondialog.cpp
 *  @brief Stores implementations of InstructionDialog class.
 *
 *  This file contains default codes generated by Qt for InstructionDialog class.
 */

#include "instructiondialog.h"
#include "ui_instructiondialog.h"

InstructionDialog::InstructionDialog(QWidget *parent) :
    QDialog(parent),
    ui(new Ui::InstructionDialog)
{
    ui->setupUi(this);
}

InstructionDialog::~InstructionDialog()
{
    delete ui;
}
