/** @file successdialog.cpp
 *  @brief Stores implementations of SuccessDialog class.
 *
 *  This file contains implementations of a slot function besides default codes generated by Qt.
 */

#include "successdialog.h"
#include "ui_successdialog.h"
#include "mainwindow.h"

SuccessDialog::SuccessDialog(QWidget *parent) :
    QDialog(parent),
    ui(new Ui::SuccessDialog)
{
    ui->setupUi(this);
}

SuccessDialog::~SuccessDialog()
{
    delete ui;
}

/** Direct the user back to the main menu after he/she clicks the button
 */
void SuccessDialog::back_to_main_menu(){
    this->hide();
    MainWindow* mainMenu = new MainWindow;
    mainMenu->setWindowTitle("Out of Inferno");
    mainMenu->show();

}
